### ISSUE TITLE
Need to change the API Structure

### ISSUE THREAD

**Issue by jayskhatri** [jayskhatri/covid19-app#2]
As this app was made in the march, that time this [api](https://github.com/covid19india/api) was in different structure. Now it's in some different structure. 

Use API of [covid19india](https://github.com/covid19india/api)

**Comment by VarunT11** [comment]
@jayskhatri Hello ! I wish to work on this issue. Would you please assign it to me?

**Comment by jayskhatri** [comment]
@VarunT11 Sure!
