### ISSUE TITLE
UI changes

### ISSUE THREAD

**Issue by jayskhatri** [jayskhatri/covid19-app#3]
If someone wants to work with UI of particular screen, feel free to work on the particular screen UI after putting the designs here✨

**Comment by AnjanaMA** [comment]
Is this issue still open for taking?

**Comment by jayskhatri** [comment]
> Is this issue still open for taking?

Yes

**Comment by jayskhatri** [comment]
@AnjanaMA Are you going to work on this issue?

**Comment by AnjanaMA** [comment]
@jayskhatri I'd be glad to.

**Comment by jayskhatri** [comment]
Great! First are you going to design the UI?

**Comment by AnjanaMA** [comment]
Yes, I would be using figma for the same.

**Comment by jayskhatri** [comment]
> 
> 
> Yes, I would be using Figma for designing the same.

Cool, you can setup the project so you can know the structure of the project. After that you can start with designing of one particular screen. Once you complete that design. You can send picture here :) If any change is there then will let you know otherwise you can go with the implementation✨ Let me know if that's okay!

**Comment by AnjanaMA** [comment]
@jayskhatri I have designed two screens heres the Figma file for it- [LINK]

I have made two alternative home pages, please suggest the due changes needed

(https://www.figma.com/file/jFaBUkZXAqbEprtLADjfHf/Untitled?node-id=0%3A1)
![HOME-1](https://user-images.githubusercontent.com/47097652/96375853-30b88680-1199-11eb-8719-951baa05c63d.png)
![LANDING](https://user-images.githubusercontent.com/47097652/96375855-31e9b380-1199-11eb-8719-6425c9032868.png)
![STATE](https://user-images.githubusercontent.com/47097652/96375856-32824a00-1199-11eb-98e8-6f4a6bf73728.png)
![HOME](https://user-images.githubusercontent.com/47097652/96375858-331ae080-1199-11eb-95c3-e8b9172ab460.png)

**Comment by jayskhatri** [comment]
Hey @AnjanaMA design looks good, though can you try different colors? try to make design minimal.

**Comment by AnjanaMA** [comment]
can you describe what particular design theme you are looking for(for ex: light theme or materialistic design )?

**Comment by jayskhatri** [comment]
I am not that much good with design terminologies, but surely light colors(light grey, white, etc.) with materialistic design will work. 👍

**Comment by AnjanaMA** [comment]
![LANDING](https://user-images.githubusercontent.com/47097652/96903261-3cff5500-14b3-11eb-9367-da7b7e251607.png)
![HOME](https://user-images.githubusercontent.com/47097652/96903303-4c7e9e00-14b3-11eb-9183-210d6852b5d3.png)
![STATE_1](https://user-images.githubusercontent.com/47097652/96903318-530d1580-14b3-11eb-90c3-a0509570877b.png)
![DOC](https://user-images.githubusercontent.com/47097652/96903336-57d1c980-14b3-11eb-9aaa-475af30fe659.png)


P.S the background components can be removed if its too complex.

**Comment by jayskhatri** [comment]
@AnjanaMA It's just awesome ✨💯 I see lot of efforts⚡👏👏

Just one little change😬

![image](https://user-images.githubusercontent.com/38436564/96903966-1ee62480-14b4-11eb-8777-9d4c49929e9b.png)

Any alternative of green color here, because in statewise card it does not look that much attractive. Also the white font on that light green color are somewhat not visible. Let me know what are your thoughts on that :)

**Comment by AnjanaMA** [comment]
![STATE_2](https://user-images.githubusercontent.com/47097652/96909455-b00cc980-14bb-11eb-8720-efb1a9fccc4b.png)
How about now?

**Comment by jayskhatri** [comment]
> 
> 
> ![STATE_2](https://user-images.githubusercontent.com/47097652/96909455-b00cc980-14bb-11eb-8720-efb1a9fccc4b.png)
> How about now?

No previous one is better then this😅

**Comment by AnjanaMA** [comment]
an alternative black text on light green
![STATE_3](https://user-images.githubusercontent.com/47097652/96910939-cc116a80-14bd-11eb-9a3b-64a09403b3f5.png)
I checked the WCAG rating of the color here and got a ratio of 10.28:1 and AAA rating

**Comment by jayskhatri** [comment]
Yeah it looks great🔥 awesome work @AnjanaMA 👏👏

From when will you be able to start implementing design in the android?

**Comment by AnjanaMA** [comment]
I can make a prototype but unfortunately, I cant work on the XML now.
