### ISSUE TITLE
Need to change images and illustrations in the self test activity

### ISSUE THREAD

**Issue by jayskhatri** [jayskhatri/covid19-app#4]

**Comment by Rounak122** [comment]
Hi, I wanted to work on this issue, but I am having a problem setting up the environment, google-services.json file is not present.

**Comment by jayskhatri** [comment]
You can get that file by creating firebase project

**Comment by Rounak122** [comment]
Thanks :) It's working now. Can I start working on this issue?

**Comment by jayskhatri** [comment]
@Rounak122 are you going to design all the illustrations?

**Comment by Rounak122** [comment]
@jayskhatri Yes, I have downloaded free illustrations and I have modified through adobe illustrator the ones which required changes. 
These are the pictures I will use:
https://drive.google.com/drive/folders/1uZ8kag38vtAggASnuPFDF6ZCI4zpkYJk?usp=sharing

**Comment by jayskhatri** [comment]
Cool @Rounak122 ✨

**Comment by jayskhatri** [comment]
Fixed in #7
