### ISSUE TITLE
Redesigning card layout to accomodate all the information

### ISSUE THREAD

**Issue by jayskhatri** [jayskhatri/covid19-app#6]
![image](https://user-images.githubusercontent.com/38436564/96331776-b810d780-107d-11eb-8d3b-569e2bb1f1ce.png)

This is the card design in which all the statistics is shown. Need to redesign it so the UI looks proper.

Please before working on implementation, don't forget to send the design over here. So changes can be accommodated in the design phase itself :)

**Comment by Rounak122** [comment]
I can work on this

**Comment by jayskhatri** [comment]
Awesome @Rounak122 , Please try to make the design that can handle overflow better, it would be great if you post design here before the implementation ✨

**Comment by rounaakk** [comment]
Hi @jayskhatri, I have modified the card layout. Please check if it is good or I need to do some more changes.

card - https://drive.google.com/drive/folders/15ZYEyVeozV8YfOtTr-wrnxQIedaH2pwC?usp=sharing

**Comment by jayskhatri** [comment]
I am not sure that if this design can handle overflow in the smaller screens, it will create same problem like the previous one. What do you think @Rounak122 ?

**Comment by rounaakk** [comment]
@jayskhatri in that case we can put the +5000 below the main text, left aligned. should i do it?

**Comment by rounaakk** [comment]
Hi @jayskhatri I have uploaded a modified version of the card at https://drive.google.com/drive/folders/15ZYEyVeozV8YfOtTr-wrnxQIedaH2pwC?usp=sharing
please check if it is ok.

**Comment by jayskhatri** [comment]
Cool you can do it, though if you get some unique idea feel free to try hands on that :)
