### ISSUE TITLE
add freepik.com in special thanks page

### ISSUE THREAD

**Issue by rounaakk** [jayskhatri/covid19-app#8]
the images in the self-test activity are taken from freepik.com. so I think we need to add it to the special thanks page

**Comment by rounaakk** [comment]
@jayskhatri I can work on this if required.

**Comment by jayskhatri** [comment]
@Rounak122, You mean designing whole new activity of special thanks?🙄

**Comment by rounaakk** [comment]
No, @jayskhatri we can add it to the about page under the special thanks heading.

**Comment by jayskhatri** [comment]
Cool @Rounak122 👍 you can proceed
